# 1. Crée un "utilisateur" pour Jenkins
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent

---
# 2. Définit un rôle qui a tous les droits nécessaires pour déployer
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-deployer
rules:
  - apiGroups: ["", "apps", "extensions", "networking.k8s.io"]
    resources: ["*"]
    verbs: ["*"]

---
# 3. Lie l'utilisateur "jenkins-agent" au rôle "jenkins-deployer"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-deployer-binding
subjects:
  - kind: ServiceAccount
    name: jenkins-agent
    namespace: default
roleRef:
  kind: ClusterRole
  name: jenkins-deployer
  apiGroup: rbac.authorization.k8s.io