apiVersion: v1
kind: Secret
metadata:
  name: jenkins-agent-token # On lui donne un nom simple
  annotations:
    kubernetes.io/service-account.name: jenkins-agent # On le lie au ServiceAccount
type: kubernetes.io/service-account-token