apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData: # Kubernetes encode automatiquement ces valeurs
  POSTGRES_DB: job_tracker
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: emsi